[pytest]
addopts = -m "not perf" --cov=app --cov-report=term-missing:skip-covered --cov-report=html -n auto
asyncio_mode = strict
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
markers =
	perf: performance tests (deselected by default)
