from typing import Protocol

from app.domain.entities import AuthorEntity, BookEntity
from app.domain.value_objects import (
    AuthorCreateData,
    AuthorUpdateData,
    BookCreateData,
    BookUpdateData,
    PaginationParams,
    PaginatedResult,
)


class ICacheService(Protocol):
    """Interface for caching service."""
    async def connect(self) -> None: ...
    async def get_books_page(self, page: int, size: int) -> PaginatedResult[BookEntity] | None: ...
    async def set_books_page(self, page: int, size: int, result: PaginatedResult[BookEntity]) -> None: ...
    async def invalidate_books_cache(self) -> None: ...
    async def get_authors_page(self, page: int, size: int) -> PaginatedResult[AuthorEntity] | None: ...
    async def set_authors_page(self, page: int, size: int, result: PaginatedResult[AuthorEntity]) -> None: ...
    async def invalidate_authors_cache(self) -> None: ...


class IBookRepository(Protocol):
    async def get_by_id(self, book_id: int) -> BookEntity | None: ...
    async def get_by_title(self, title: str) -> BookEntity | None: ...
    async def get_paginated(self, pagination: PaginationParams) -> PaginatedResult[BookEntity]: ...
    async def create(self, book_data: BookCreateData) -> BookEntity: ...
    async def update(self, book_id: int, book_data: BookUpdateData) -> BookEntity | None: ...
    async def delete(self, book_id: int) -> bool: ...


class IAuthorRepository(Protocol):
    async def get_by_id(self, author_id: int) -> AuthorEntity | None: ...
    async def get_by_full_name(self, first_name: str, last_name: str) -> AuthorEntity | None: ...
    async def get_paginated(self, pagination: PaginationParams, search: str | None = None) -> PaginatedResult[AuthorEntity]: ...
    async def create(self, author_data: AuthorCreateData) -> AuthorEntity: ...
    async def update(self, author_id: int, author_data: AuthorUpdateData) -> AuthorEntity | None: ...
    async def delete(self, author_id: int) -> bool: ...
    async def partial_update(self, author_id: int, author_data: AuthorUpdateData) -> AuthorEntity | None: ...
